### PR TITLE
FIX: Correct python used to check NWB file

### PR DESCRIPTION
**Pull request by KatharineShapcott**
Same fix as in syncopy _load_nwb

### CODE REVIEW

**Review by pantaray — APPROVED** [review]
Looks good, thanks for the fix!

**Comment by KatharineShapcott** [comment]
Thanks! Do you know when you'll manage to update pip? I'll start making a conda environment for the whole lab soon, wondering if I should use pip or github for this

**Comment by pantaray** [comment]
Hi! I'm not sure what you mean by update pip? The code is not yet on PyPI. Do you want me to upload it so it can be pip installed?

**Comment by KatharineShapcott** [comment]
According to the documentaiton it is! ;) I'm pretty sure that's where I installed it from `pip install esi-oephys2nwb`

**Comment by pantaray** [comment]
The documentation is, ahem, "future proof" - the package is not yet on PyPI - I guess you did a `git clone` followed by `pip install .`. I'll prepare everything and push it to PyPI :)

**Comment by pantaray** [comment]
Took a little polishing but the package is now online: https://pypi.org/project/esi-oephys2nwb/2022.5rc0/ so `pip install` should work as expected :) I updated the README accordingly

**Pull request merged**
